config/routes.rb
Rails.application.routes.draw do

  get 'utils/erd', to: 'utils#erd'

  resources :scores
  post 'scores/quick_add', to: 'scores#quick_add'
  get  'scoresheet/:id', to: 'scores#scoresheet'

  resources :persons
  resources :users
  resources :sessionyears do
    resources :registrations
  end
  resources :registrations

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Sessions / login
  resources :sessions
  get  'calendar/:id', to: 'sessionyears#calendar'
  post 'calendar/:id', to: 'sessionyears#calendar'

  root :to => 'registrations#index'
end

app/models/sessionyear.rb
class Sessionyear < ApplicationRecord

  has_many :sessiondays
  has_many :registrations

  scope :sorted, -> { order('start_date desc') }

  validates_presence_of :start_date
  validates_presence_of :end_date

  #
  def self.current
    where(['start_date < ? and end_date > ?', Time.now, Time.now]).first
  end
  def self.current_or_next
    where(['end_date > ?', Time.now]).order('end_date ASC').first
  end

  def self.vals_for_select
    vals = []
    sorted.limit(5).each do |sy|
      vals << [sy.year_with_theme, sy.id]
    end
    return vals
  end

  def year
    "#{start_date.to_formatted_s(:year)}-#{end_date.to_formatted_s(:year)}"
  end

  def year_with_theme
    "#{year} #{theme}"
  end

  def has_cal?
    return sessiondays.count > 0
  end

  # Given a date, return the sessionday club night if exists
  def club_night_on(date)
    sessiondays.where(sd_date: date).club_nights.first
  end


end

app/controllers/sessionyears_controller.rb
class SessionyearsController < ApplicationController

  ACCESS = {
    edit_calendar: [:calendar, :index, :show, :new, :edit, :create, :update, :destroy]
  }
  before_action -> { authorize(ACCESS) }

  before_action :set_sessionyear, only: [:show, :edit, :update, :destroy,
                                          :calendar, :generate_calendar]

  def calendar

    # Generate stub calendar. Should only be called 1x per SY
    if @sessionyear.sessiondays.count == 0
      CalBuilder.build_draft(@sessionyear)
      @sessionyear.sessiondays.each {|sd| sd.save! }
    end

  end

  # GET /sessionyears
  # GET /sessionyears.json
  def index
    @sessionyears = Sessionyear.sorted
  end

  # GET /sessionyears/1
  # GET /sessionyears/1.json
  def show
  end

  # GET /sessionyears/new
  def new
    @sessionyear = Sessionyear.new
  end

  # GET /sessionyears/1/edit
  def edit
  end

  # POST /sessionyears
  # POST /sessionyears.json
  def create
    @sessionyear = Sessionyear.new(sessionyear_params)

    respond_to do |format|
      if @sessionyear.save
        format.html { redirect_to @sessionyear, notice: 'Sessionyear was successfully created.' }
        format.json { render :show, status: :created, location: @sessionyear }
      else
        format.html { render :new }
        format.json { render json: @sessionyear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessionyears/1
  # PATCH/PUT /sessionyears/1.json
  def update
    respond_to do |format|
      if @sessionyear.update(sessionyear_params)
        format.html { redirect_to @sessionyear, notice: 'Sessionyear was successfully updated.' }
        format.json { render :show, status: :ok, location: @sessionyear }
      else
        format.html { render :edit }
        format.json { render json: @sessionyear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessionyears/1
  # DELETE /sessionyears/1.json
  def destroy
    @sessionyear.destroy
    respond_to do |format|
      format.html { redirect_to sessionyears_url, notice: 'Sessionyear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sessionyear
      @sessionyear = Sessionyear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sessionyear_params
      params.fetch(:sessionyear, {}).permit(:start_date, :end_date, :theme)
    end
end

app/views/sessionyears/_form.html.erb
<%= form_for(sessionyear) do |f| %>
  <% if sessionyear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sessionyear.errors.count, "error") %> prohibited this sessionyear from being saved:</h2>

      <ul>
      <% sessionyear.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :theme %>
    <%= f.text_field :theme, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.datetime_field :start_date, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.datetime_field :end_date, class:"form-control" %>
  </div>

  <%= link_to 'Cancel', sessionyears_path, class:"btn btn-secondary" %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/sessionyears/calendar.html.erb
<h1><%= @sessionyear.year %> Calendar</h1>
Theme: <%= @sessionyear.theme %>

<table class="table table-hover table-condensed">
  <tr>
     <th>Date</th>
     <th>Lesson</th>
     <th>Events</th>
  </tr>
  <% #@sessionyear.make_new_stub_cal
     #CalBuilder.build_draft(@sessionyear)
     mgr = K4tLessonMgr.new
  %>
  <% @sessionyear.sessiondays.each do |sd| %>
    <tr class="<%= sd.is_club_night? ? 'stronger' : 'weaker' %> <%= sd.is_current? ? 'info' : '' %>">
      <td><%= sd.sd_date.to_formatted_s :mdy %></td>
      <td>
        <% if sd.is_club_night? %>
          <%  lesson =  mgr.next_b %>
          <%= lesson[:name] %>
        <% else %>
          No K4T
        <% end %>
      </td>
      <td><%= '' %>Event
        <div class="btn-group">
          <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add event <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">Action 1</a></li>
            <li><a href="#">Action 2</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Other thing</a></li>
          </ul>
        </div>
      </td>
    </tr>
<% end %>
</table>

<%= link_to 'Back', sessionyears_path %>

app/views/sessionyears/edit.html.erb
<h1>Editing Sessionyear</h1>

<%= render 'form', sessionyear: @sessionyear %>

app/views/sessionyears/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sessionyears</h1>

<table class="<%= tbl_css %>">

  <tbody>
    <tr>
      <th>Year</th>
      <th>Theme</th>
      <th>Calendar</th>
      <th>Dates</th>
      <th>Reg Count</th>
      <th>Avg Att</th>
      <th></th>
      <th></th>
    </tr>
    <% now = Time.now %>
    <% @sessionyears.each do |sessionyear| %>
      <tr class="<%= (now.between?(sessionyear.start_date, sessionyear.end_date)) ? 'alert alert-info' : '' %>">
        <td>
          <%= link_to sessionyear.year, sessionyear %>
        </td>
        <td><%= sessionyear.theme %></td>
        <td>
          <% if sessionyear.has_cal? %>
            <a href="/calendar/<%= sessionyear.id %>">View Calendar</a>
          <% else %>
            <%= button_to 'Generate',("/calendar/#{sessionyear.id}"), method: :post, class:"btn btn-primary" %>
          <% end %>
        </td>
        <td>
          <%= sessionyear.start_date.to_formatted_s :mdy %> -
          <%= sessionyear.end_date.to_formatted_s :mdy %>
        </td>
        <td>todo</td>
        <td>todo</td>
        <td><%= link_to 'Edit', edit_sessionyear_path(sessionyear) %></td>
        <td><%= link_to 'Destroy', sessionyear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sessionyear', new_sessionyear_path, class: "btn btn-primary" %>

app/views/sessionyears/new.html.erb
<h1>New Sessionyear</h1>

<%= render 'form', sessionyear: @sessionyear %>

<%= link_to 'Back', sessionyears_path %>

app/views/sessionyears/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @sessionyear.year %> Calendar</h1>
Theme: <%= @sessionyear.theme %>


<%= link_to 'Edit', edit_sessionyear_path(@sessionyear) %> |
<%= link_to 'Back', sessionyears_path %>