config/routes.rb
Rails.application.routes.draw do

  get 'utils/erd', to: 'utils#erd'

  resources :scores
  post 'scores/quick_add', to: 'scores#quick_add'
  get  'scoresheet/:id', to: 'scores#scoresheet'

  resources :persons
  resources :users
  resources :sessionyears do
    resources :registrations
  end
  resources :registrations

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Sessions / login
  resources :sessions
  get  'calendar/:id', to: 'sessionyears#calendar'
  post 'calendar/:id', to: 'sessionyears#calendar'

  root :to => 'registrations#index'
end

app/models/person.rb
class Person < ApplicationRecord

  has_one    :user
  has_many   :registrations
  has_many   :truthbooksignatures, :class_name=> "Truthbooksignature", :foreign_key=>'clubber_id'
  has_many   :scores, :class_name=>"Score", :foreign_key=>'clubber_id'
  has_many   :vwscores, :class_name=>"Vwscore", :foreign_key=>'clubber_id'

  scope :sorted, lambda { order('last_name, first_name') }

  def name_lf
    Person.name_lf(last_name, first_name)
  end
  def name_fl
    Person.name_fl(last_name, first_name)
  end
  def self.name_lf(ln, fn)
    [ln, fn].delete_if{|n| n.blank?}.join(', ')
  end
  def self.name_fl(ln, fn)
    [fn, ln].delete_if{|n| n.blank?}.join(' ')
  end

  def current_registration()
    @current_registration ||= Registration.for_person_in(self, Sessionyear.current).first
  end

=begin
  def current_truthbook_section
    @current_truthbook_section ||=  Truthbooksection.current_tbsec_sort_for_user_sql ...NEEDED? TODO
  end
=end

  def current_truthbook
    return @current_truthbook unless @current_truthbook.nil?
    sub_sql = Truthbooksection.current_tbsec_sort_for_user_sql(self.id)
    tb = Truthbook.where("(truthbooksections.sort-1) = #{sub_sql}").joins(:truthbooksections).first
    @current_truthbook = tb || Truthbook.new # blank book

  end

  def next_truthbook_section_sort_id
    (truthbooksignatures.joins(:truthbooksection).maximum('truthbooksections.sort') || 0) + 1
  end

  # TODO include skipped sections first!!!
  def next_truthbook_sections(how_many=5)
    tbk_start_sort = Truthbooksection.start_sort_for_book(self.current_truthbook)
    Truthbooksection.
      joins("LEFT JOIN truthbooksignatures signas ON (signas.truthbooksection_id = truthbooksections.id and signas.clubber_id = #{self.id} )").
      where("signas.id is null").
      where(["sort >= ?", tbk_start_sort]).sorted.limit(how_many)
  end

  def current_points
    return @current_points if @current_points.present?
    sy = Sessionyear.current
    return @current_points = 0 if sy.nil?
    @current_points = Vwscore.scores_for(self, Sessionyear.current).sum(:point_value)
  end

  def self.for_clubber_select
    Person.joins(:registrations).where("reg_type='Clubber'").order('registrations.id DESC, Persons.last_name')
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  ACCESS = {
    edit_persons: [:index, :show, :new, :edit, :create, :update, :destroy]
  }
  before_action -> { authorize(ACCESS) }

  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /persons
  # GET /persons.json
  def index
    @persons = Person.all
  end

  # GET /persons/1
  # GET /persons/1.json
  def show
  end

  # GET /persons/new
  def new
    @person = Person.new
  end

  # GET /persons/1/edit
  def edit
  end

  # POST /persons
  # POST /persons.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /persons/1
  # PATCH/PUT /persons/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /persons/1
  # DELETE /persons/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to persons_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.fetch(:person, {}).permit(:first_name, :last_name)
    end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/persons/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class:"form-control" %>
  </div>

  <%= link_to 'Cancel', persons_path, class:'btn btn-secondary', role:'button' %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/persons/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

app/views/persons/index.html.erb
<h1>All People</h1>

<table class="<%= tbl_css %>">
  <tbody>
    <% @persons.each do |person| %>
      <tr>
        <td><%= link_to person.name_lf, person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <!--<td><%#= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <td><%= link_to 'Register Clubber!', "/registrations/new?person_id=#{person.id}&type=clubber" %></td>
        <td><%= link_to 'Register Leader!', "/registrations/new?person_id=#{person.id}&type=leader" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path, class:"btn btn-primary" %>

app/views/persons/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', persons_path %>

app/views/persons/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Person: <%= @person.name_lf %> </h1>
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', persons_path %>