config/routes.rb
Rails.application.routes.draw do

  get 'utils/erd', to: 'utils#erd'

  resources :scores
  post 'scores/quick_add', to: 'scores#quick_add'
  get  'scoresheet/:id', to: 'scores#scoresheet'

  resources :persons
  resources :users
  resources :sessionyears do
    resources :registrations
  end
  resources :registrations

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Sessions / login
  resources :sessions
  get  'calendar/:id', to: 'sessionyears#calendar'
  post 'calendar/:id', to: 'sessionyears#calendar'

  root :to => 'registrations#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Harfin</title>
    <%= csrf_meta_tags %>

    <!-- mobile first design - touch zoomingi & page width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">TBC K4T</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <% if current_user.has_priv? :edit_persons %> <%# TODO need admin priv %>
            <li class="nav-item"><%= link_to "Persons", :persons, class: 'nav-link' %></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" >
                Registrations
              </a>
              <div class="dropdown-menu">
                <%= link_to "Clubbers", :registrations, :class=> 'dropdown-item' %>
                <a class="dropdown-item" href="#">Leaders</a>
              </div>
            </li>
            <li class="nav-item"><%= link_to "Session Years", :sessionyears, class: 'nav-link' %></li>

          <% else %>
            <li class="nav-item"><%= link_to "Registrations", :registrations, class: 'nav-link' %></li>
          <% end %>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="nav-item"><a class="nav-link" href="#"><%= current_user.email %></a></li>
            <li class="nav-item"><%= link_to "Log Out", logout_path, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign Up", signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Log In", login_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </nav>


    <div class="container-fluid p-3">
      <% if flash[:notice].present? %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert].present? %>
        <div class="alert alert-warning "><%= flash[:alert] %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>